# Generated by Django 5.0.3 on 2024-09-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('classe', models.CharField(choices=[('1A', 'Classe 1A'), ('1B', 'Classe 1B')], max_length=50)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('nom_pere', models.CharField(max_length=100)),
                ('nom_mere', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
