# Generated by Django 5.0.3 on 2024-09-17 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_classes_alter_student_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_annee', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='annee_scolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire'),
        ),
        migrations.AddField(
            model_name='student',
            name='annee_scolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('object_paiement', models.CharField(max_length=50)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('recu', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.student')),
            ],
        ),
    ]
