# Generated by Django 5.0.3 on 2024-09-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_anneescolaire_classes_annee_scolaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mois',
            field=models.CharField(max_length=20),
        ),
    ]
