# Generated by Django 5.0.3 on 2024-09-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_paiement_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.classes'),
        ),
    ]
