# Generated by Django 5.0.3 on 2024-09-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_paiement_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='annee_scolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire'),
        ),
    ]
