# Generated by Django 5.0.3 on 2024-09-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_paiement_annee_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mois',
            field=models.CharField(choices=[('janvier', 'Janvier'), ('février', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('août', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('décembre', 'Décembre')], max_length=20),
        ),
    ]
