# Generated by Django 5.0.3 on 2024-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_paiement_mois'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('minerval', 'Minerval'), ('autre_frais', 'Autre Frais')], default='autre_frais', max_length=20),
        ),
    ]
