# Generated by Django 5.2 on 2025-07-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_alter_classes_options_anneescolaire_total_depenses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutreFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant_cdf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='total_depenses_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='total_revenu_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='montant_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='depense',
            name='montant_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='devise',
            field=models.CharField(choices=[('cdf', 'Franc Congolais'), ('usd', 'Dollar')], default='cdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='total_depenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='total_revenu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
