# Generated by Django 5.2 on 2025-07-07 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_autrefrais_anneescolaire_total_depenses_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autrefrais',
            name='annee_scolaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire'),
        ),
    ]
