# Generated by Django 5.2 on 2025-07-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_autrefrais_annee_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='montant_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
