# Generated by Django 5.2 on 2025-07-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_alter_classes_montant_alter_classes_montant_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='devise',
            field=models.CharField(choices=[('cdf', 'Franc Congolais'), ('usd', 'Dollar'), ('mixte', 'Mixte')], default='cdf', max_length=10),
        ),
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Taux de conversion USD → CDF', max_digits=10)),
                ('date_taux', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='taux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.taux'),
        ),
    ]
