# Generated by Django 5.2 on 2025-07-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_alter_paiement_devise_taux_paiement_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='montant_cdf_brut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_usd_brut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
