# Generated by Django 5.2 on 2025-07-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_paiement_montant_cdf_brut_paiement_montant_usd_brut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autrefrais',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.user'),
        ),
        migrations.AddField(
            model_name='classes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.user'),
        ),
        migrations.AddField(
            model_name='depense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.user'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.user'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.user'),
        ),
        migrations.AddField(
            model_name='taux',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('promo', 'Admin École'), ('comptable', 'Comptable')], default='comptable', max_length=20),
        ),
        migrations.AlterField(
            model_name='autrefrais',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.classes'),
        ),
        migrations.AlterField(
            model_name='student',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='taux',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire'),
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.ecole'),
        ),
        migrations.AddField(
            model_name='user',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.ecole'),
        ),
    ]
