# Generated by Django 5.2 on 2025-08-06 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.anneescolaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions_crees', to=settings.AUTH_USER_MODEL)),
                ('user_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions_utilisables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('description', 'annee_scolaire', 'user_cible')},
            },
        ),
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.descriptiondepense'),
        ),
    ]
