# Generated by Django 5.2 on 2025-08-06 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_descriptiondepense_alter_depense_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='descriptiondepense',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='descriptiondepense',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.ecole'),
        ),
        migrations.RemoveField(
            model_name='descriptiondepense',
            name='created_by',
        ),
    ]
