# Generated by Django 5.2 on 2025-08-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_alter_descriptiondepense_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='descriptiondepense',
            unique_together={('description', 'ecole', 'annee_scolaire', 'user_cible')},
        ),
    ]
